name: Playwright Async Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies + Playwright browsers
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-playwright pytest-xdist allure-pytest
        pip install playwright

        # Установка Playwright браузеров
        python -m playwright install --with-deps

    - name: Run tests
      run: |
        pytest -n auto --browser=${{ matrix.browser }}

    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.browser }}
        path: artifacts/allure-results/

    - name: Install Allure CLI
      if: always()
      uses: allure-framework/setup-allure@v1
      with:
        version: 2.22.2

    - name: Generate Allure Report
      if: always()
      run: |
        allure generate artifacts/allure-results --clean -o allure-report || true
        zip -r allure-report-${{ matrix.browser }}.zip allure-report
      shell: bash

    - name: Upload Allure HTML artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-html-${{ matrix.browser }}
        path: allure-report-${{ matrix.browser }}.zip



