name: Playwright Async Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies + Playwright browsers
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest pytest-xdist pytest-playwright
        pip install playwright

        # Установка браузеров Playwright
        npx playwright install --with-deps

    - name: Run tests
      run: |
        pytest -n auto --browser=${{ matrix.browser }}

    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.browser }}
        path: artifacts/allure-results/

    - name: Install Allure CLI
      if: always()
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.22.2/allure-2.22.2.zip
        unzip allure-2.22.2.zip -d allure
        chmod +x allure/bin/allure

    - name: Generate Allure HTML Report
      if: always()
      run: |
        allure/bin/allure generate artifacts/allure-results -o allure-report || true
        zip -r allure-report-${{ matrix.browser }}.zip allure-report
      shell: bash

    - name: Upload Allure HTML artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-html-${{ matrix.browser }}
        path: allure-report-${{ matrix.browser }}.zip

